export const timerRecords = [
  {
    id: "special-cargo-source",
    category: "CEO & Cargo",
    activity: "Special Cargo sourcing",
    timerType: "Activity cooldown",
    duration: "5 min",
    minMinutes: 5,
    trigger: "A crate source mission ends for the selected warehouse.",
    scope: "property",
    scopeLabel: "Per warehouse",
    parallel: "yes",
    parallelLabel: "Yes — source for another warehouse or run other work.",
    conditions: "The lockout belongs to the warehouse used for that mission, not every cargo warehouse you own.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Special Cargo", url: "https://gta.fandom.com/wiki/Special_Cargo" }],
    verified: "2026-08-30"
  },
  {
    id: "warehouse-staff-source",
    category: "CEO & Cargo",
    activity: "Warehouse Staff cargo sourcing",
    timerType: "Passive production",
    duration: "48 min",
    minMinutes: 48,
    trigger: "You pay Lupe or another warehouse staff member to source cargo.",
    scope: "property",
    scopeLabel: "Per warehouse staff member",
    parallel: "yes",
    parallelLabel: "Yes — the staff timer continues during other work and while offline.",
    conditions: "The staff member returns with 1–3 normal crates and may also find a special item. A full warehouse blocks delivery.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Special Cargo", url: "https://gta.fandom.com/wiki/Special_Cargo" }, { label: "PC Gamer — GTA Online money guide", url: "https://www.pcgamer.com/how-to-make-money-in-gta-online/" }],
    verified: "2026-08-30"
  },
  {
    id: "mixed-goods-cooldown",
    category: "CEO & Cargo",
    activity: "Export Mixed Goods",
    timerType: "Activity cooldown",
    duration: "48 min",
    minMinutes: 48,
    trigger: "The Mixed Goods export succeeds or fails.",
    scope: "activity",
    scopeLabel: "This export activity",
    parallel: "yes",
    parallelLabel: "Yes — Special Cargo sourcing and other businesses remain available.",
    conditions: "The timer is independent of warehouse stock and starts on failure too. The export itself has a 15-minute mission limit.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Export Mixed Goods", url: "https://gta.fandom.com/wiki/Export_Mixed_Goods" }],
    verified: "2026-08-30"
  },
  {
    id: "mixed-goods-mission",
    category: "CEO & Cargo",
    activity: "Export Mixed Goods delivery",
    timerType: "Mission time limit",
    duration: "15 min",
    minMinutes: 15,
    trigger: "You launch Export Mixed Goods from the Office assistant.",
    scope: "activity",
    scopeLabel: "Current mission",
    parallel: "no",
    parallelLabel: "No — complete or fail the active delivery first.",
    conditions: "Losing the Flatbed or letting the timer expire fails the export and starts its 48-minute cooldown.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Export Mixed Goods", url: "https://gta.fandom.com/wiki/Export_Mixed_Goods" }],
    verified: "2026-08-30"
  },
  {
    id: "vehicle-cargo-source",
    category: "CEO & Cargo",
    activity: "Vehicle Cargo sourcing",
    timerType: "Activity cooldown",
    duration: "2 min 30 sec",
    minMinutes: 2.5,
    trigger: "A vehicle retrieval succeeds or fails.",
    scope: "activity",
    scopeLabel: "Vehicle Warehouse sourcing",
    parallel: "yes",
    parallelLabel: "Yes — exports and unrelated work remain available.",
    conditions: "The cooldown begins when the vehicle reaches the warehouse or when the retrieval fails.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Vehicle Cargo", url: "https://gta.fandom.com/wiki/Vehicle_Cargo" }],
    verified: "2026-08-30"
  },
  {
    id: "vehicle-cargo-export",
    category: "CEO & Cargo",
    activity: "Vehicle Cargo exporting",
    timerType: "Activity cooldown",
    duration: "20–50 min",
    minMinutes: 20,
    trigger: "The organization completes a vehicle export.",
    scope: "activity",
    scopeLabel: "Vehicle Warehouse exports",
    parallel: "yes",
    parallelLabel: "Yes — source vehicles or run other businesses.",
    conditions: "The cooldown increases with the number of vehicles exported together: one to four vehicles produces the 20–50 minute range.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Vehicle Cargo sell missions", url: "https://gta.fandom.com/wiki/Vehicle_Cargo/Sell_Missions" }],
    verified: "2026-08-30"
  },
  {
    id: "vehicle-cargo-delivery-limit",
    category: "CEO & Cargo",
    activity: "Vehicle Cargo export delivery",
    timerType: "Mission time limit",
    duration: "15 min",
    minMinutes: 15,
    trigger: "The export vehicle leaves the Vehicle Warehouse.",
    scope: "activity",
    scopeLabel: "Current export",
    parallel: "no",
    parallelLabel: "No — the export must finish first.",
    conditions: "The modification step has its own five-minute limit before the 15-minute delivery clock.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Vehicle Cargo sell missions", url: "https://gta.fandom.com/wiki/Vehicle_Cargo/Sell_Missions" }],
    verified: "2026-08-30"
  },
  {
    id: "vip-work-global",
    category: "CEO & Cargo",
    activity: "VIP / CEO Work — different job",
    timerType: "Activity cooldown",
    duration: "5 min",
    minMinutes: 5,
    trigger: "A VIP / CEO Work job ends.",
    scope: "global",
    scopeLabel: "Across regular VIP / CEO Work",
    parallel: "yes",
    parallelLabel: "Yes — businesses and most unrelated activities remain available.",
    conditions: "Starting the same job again normally uses the longer 10-minute timer. Certain jobs have their own longer rules.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Organizations", url: "https://gta.fandom.com/wiki/Organizations" }],
    verified: "2026-08-30"
  },
  {
    id: "vip-work-same",
    category: "CEO & Cargo",
    activity: "VIP / CEO Work — same job",
    timerType: "Activity cooldown",
    duration: "10 min",
    minMinutes: 10,
    trigger: "You finish a regular VIP / CEO Work job and try to repeat that same job.",
    scope: "activity",
    scopeLabel: "Per VIP / CEO Work job",
    parallel: "yes",
    parallelLabel: "Yes — select a different eligible job after the global five-minute wait.",
    conditions: "Piracy Prevention is an important exception with a 60-minute cooldown.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Organizations", url: "https://gta.fandom.com/wiki/Organizations" }],
    verified: "2026-08-30"
  },
  {
    id: "piracy-prevention",
    category: "CEO & Cargo",
    activity: "Piracy Prevention",
    timerType: "Activity cooldown",
    duration: "60 min",
    minMinutes: 60,
    trigger: "Piracy Prevention ends.",
    scope: "activity",
    scopeLabel: "This VIP / CEO Work job",
    parallel: "yes",
    parallelLabel: "Yes — the rest of the criminal network can still be used.",
    conditions: "This is the notable longer exception to regular VIP / CEO Work cooldowns.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Organizations", url: "https://gta.fandom.com/wiki/Organizations" }],
    verified: "2026-08-30"
  },
  {
    id: "client-jobs-global",
    category: "Terrorbyte",
    activity: "Client Jobs — different job",
    timerType: "Activity cooldown",
    duration: "5 min",
    minMinutes: 5,
    trigger: "A solo-capable Terrorbyte Client Job ends.",
    scope: "global",
    scopeLabel: "Across regular Client Jobs",
    parallel: "yes",
    parallelLabel: "Yes — use the gap for business work or another activity type.",
    conditions: "Client Challenges have separate shorter cross-job rules and require multiple players.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Client Jobs", url: "https://gta.fandom.com/wiki/Client_Jobs" }],
    verified: "2026-08-30"
  },
  {
    id: "client-jobs-same",
    category: "Terrorbyte",
    activity: "Client Jobs — same job",
    timerType: "Activity cooldown",
    duration: "30 min",
    minMinutes: 30,
    trigger: "A Terrorbyte Client Job ends and you try to repeat it.",
    scope: "activity",
    scopeLabel: "Per Client Job",
    parallel: "yes",
    parallelLabel: "Yes — another Client Job is available after the five-minute global wait.",
    conditions: "Two-player Client Challenges use a 10-minute same-job and three-minute other-job cooldown instead.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Client Jobs", url: "https://gta.fandom.com/wiki/Client_Jobs" }],
    verified: "2026-08-30"
  },
  {
    id: "mc-bought-supplies",
    category: "MC / Biker",
    activity: "Purchased MC business supplies",
    timerType: "Supply delivery",
    duration: "10 min",
    minMinutes: 10,
    trigger: "You buy supplies from an MC business laptop or eligible remote terminal.",
    scope: "property",
    scopeLabel: "Per MC business",
    parallel: "yes",
    parallelLabel: "Yes — leave the property and do other work while delivery is pending.",
    conditions: "Production resumes when supplies arrive, provided the business is set up and not shut down.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Business Supplies", url: "https://gta.fandom.com/wiki/Business_Supplies" }],
    verified: "2026-08-30"
  },
  {
    id: "mc-cocaine-production",
    category: "MC / Biker",
    activity: "Cocaine Lockup — full stock production",
    timerType: "Passive production",
    duration: "About 5 hr",
    minMinutes: 300,
    trigger: "An upgraded, supplied Cocaine Lockup starts producing.",
    scope: "property",
    scopeLabel: "That Cocaine Lockup",
    parallel: "yes",
    parallelLabel: "Yes — production runs while you are active in GTA Online.",
    conditions: "Approximate fully upgraded time. Production pauses while offline, out of supplies, raided, or shut down.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — The Open Road", url: "https://gta.fandom.com/wiki/The_Open_Road" }, { label: "Current MC supply guide", url: "https://gamers.wiki/en/games/grand-theft-auto-v/guides/gta-online-mc-supplies-buy-vs-steal" }],
    verified: "2026-08-30"
  },
  {
    id: "mc-meth-production",
    category: "MC / Biker",
    activity: "Meth Lab — full stock production",
    timerType: "Passive production",
    duration: "About 6 hr",
    minMinutes: 360,
    trigger: "An upgraded, supplied Meth Lab starts producing.",
    scope: "property",
    scopeLabel: "That Meth Lab",
    parallel: "yes",
    parallelLabel: "Yes — production runs while you are active in GTA Online.",
    conditions: "Approximate fully upgraded time. Production pauses while offline, out of supplies, raided, or shut down.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — The Open Road", url: "https://gta.fandom.com/wiki/The_Open_Road" }, { label: "Current MC supply guide", url: "https://gamers.wiki/en/games/grand-theft-auto-v/guides/gta-online-mc-supplies-buy-vs-steal" }],
    verified: "2026-08-30"
  },
  {
    id: "mc-cash-production",
    category: "MC / Biker",
    activity: "Counterfeit Cash — full stock production",
    timerType: "Passive production",
    duration: "About 5 hr 20 min",
    minMinutes: 320,
    trigger: "An upgraded, supplied Counterfeit Cash Factory starts producing.",
    scope: "property",
    scopeLabel: "That Cash Factory",
    parallel: "yes",
    parallelLabel: "Yes — production runs while you are active in GTA Online.",
    conditions: "Approximate fully upgraded time. Money Fronts ownership can change income, not the base production clock.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — The Open Road", url: "https://gta.fandom.com/wiki/The_Open_Road" }],
    verified: "2026-08-30"
  },
  {
    id: "mc-weed-production",
    category: "MC / Biker",
    activity: "Weed Farm — full stock production",
    timerType: "Passive production",
    duration: "About 5 hr 20 min",
    minMinutes: 320,
    trigger: "An upgraded, supplied Weed Farm starts producing.",
    scope: "property",
    scopeLabel: "That Weed Farm",
    parallel: "yes",
    parallelLabel: "Yes — production runs while you are active in GTA Online.",
    conditions: "Approximate fully upgraded time. Smoke on the Water can boost value but does not remove the production requirement.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — The Open Road", url: "https://gta.fandom.com/wiki/The_Open_Road" }],
    verified: "2026-08-30"
  },
  {
    id: "mc-documents-production",
    category: "MC / Biker",
    activity: "Document Forgery — full stock production",
    timerType: "Passive production",
    duration: "About 3 hr",
    minMinutes: 180,
    trigger: "An upgraded, supplied Document Forgery Office starts producing.",
    scope: "property",
    scopeLabel: "That Forgery Office",
    parallel: "yes",
    parallelLabel: "Yes — production runs while you are active in GTA Online.",
    conditions: "Approximate fully upgraded time. Production pauses while offline, out of supplies, raided, or shut down.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — The Open Road", url: "https://gta.fandom.com/wiki/The_Open_Road" }],
    verified: "2026-08-30"
  },
  {
    id: "mc-sell-limit",
    category: "MC / Biker",
    activity: "MC business sell missions",
    timerType: "Mission time limit",
    duration: "30 min / 45 min solo",
    minMinutes: 30,
    trigger: "You launch a product sale from an MC business.",
    scope: "activity",
    scopeLabel: "Current MC sale",
    parallel: "no",
    parallelLabel: "No — the sale mission occupies the organization.",
    conditions: "The 45-minute clock applies when the MC has only one member. With another member in the MC, the standard 30-minute clock applies.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — MC sell missions", url: "https://gta.fandom.com/wiki/Business_Supplies/Sell_Missions" }, { label: "Rockstar Title Update 1.69", url: "https://support.rockstargames.com/articles/eUgRHVRSN2V9gimBT32YX/gtav-title-update-1-69-notes-ps5-ps4-xbox-series-x-s-xbox-one-pc" }],
    verified: "2026-08-30"
  },
  {
    id: "bunker-supply-delivery",
    category: "Bunker",
    activity: "Purchased Bunker supplies",
    timerType: "Supply delivery",
    duration: "10 min",
    minMinutes: 10,
    trigger: "You purchase supplies through Disruption Logistics.",
    scope: "property",
    scopeLabel: "Your Bunker",
    parallel: "yes",
    parallelLabel: "Yes — the stock arrives while you perform other activities.",
    conditions: "The timer runs in-session. Manufacturing restarts when the delivery arrives.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Bunker Supplies", url: "https://gta.fandom.com/wiki/Supplies" }],
    verified: "2026-08-30"
  },
  {
    id: "bunker-production",
    category: "Bunker",
    activity: "Bunker — full stock production",
    timerType: "Passive production",
    duration: "11 hr 40 min upgraded",
    minMinutes: 700,
    trigger: "A fully supplied Bunker assigns staff only to manufacturing.",
    scope: "property",
    scopeLabel: "Your Bunker",
    parallel: "yes",
    parallelLabel: "Yes — production runs while you remain in GTA Online.",
    conditions: "Both equipment and staff upgrades produce one of 100 stock units every seven minutes. No upgrades takes about 16 hr 40 min. Splitting staff with Research is slower.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Disruption Logistics", url: "https://gta.fandom.com/wiki/Disruption_Logistics" }],
    verified: "2026-08-30"
  },
  {
    id: "bunker-ammunation",
    category: "Bunker",
    activity: "Ammu-Nation Contract",
    timerType: "Activity cooldown",
    duration: "48 min",
    minMinutes: 48,
    trigger: "You successfully deliver the excess weapon parts.",
    scope: "activity",
    scopeLabel: "Your Bunker's delivery truck",
    parallel: "yes",
    parallelLabel: "Yes — normal Bunker production and other work continue.",
    conditions: "A failed delivery leaves the truck ready and does not start the same successful-delivery cycle.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Ammu-Nation Contract", url: "https://gta.fandom.com/wiki/Ammu-Nation_Contract" }],
    verified: "2026-08-30"
  },
  {
    id: "bunker-sell-limit",
    category: "Bunker",
    activity: "Bunker sell missions",
    timerType: "Mission time limit",
    duration: "15 or 30 min base",
    minMinutes: 15,
    trigger: "You launch a stock sale from Disruption Logistics.",
    scope: "activity",
    scopeLabel: "Current Bunker sale",
    parallel: "no",
    parallelLabel: "No — the organization is occupied by the sale.",
    conditions: "Most routes use 15 minutes; one uses 30. Solo launches receive 50% more time: 22 min 30 sec or 45 minutes.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Bunker sell missions", url: "https://gta.fandom.com/wiki/Supplies/Sell_Missions" }, { label: "Rockstar Title Update 1.69", url: "https://support.rockstargames.com/articles/eUgRHVRSN2V9gimBT32YX/gtav-title-update-1-69-notes-ps5-ps4-xbox-series-x-s-xbox-one-pc" }],
    verified: "2026-08-30"
  },
  {
    id: "hangar-manual-source",
    category: "Hangar",
    activity: "Air Freight Cargo sourcing",
    timerType: "Activity cooldown",
    duration: "2–7 min",
    minMinutes: 2,
    trigger: "An Air Freight source mission delivers cargo.",
    scope: "activity",
    scopeLabel: "Per cargo type",
    parallel: "yes",
    parallelLabel: "Yes — source a different cargo type immediately.",
    conditions: "Base cooldown by cargo tier is 2, 3, or 4 minutes for one crate, plus one minute for each extra crate delivered by additional members.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Air Freight Cargo", url: "https://gta.fandom.com/wiki/Air_Freight_Cargo" }],
    verified: "2026-08-30"
  },
  {
    id: "hangar-source-limit",
    category: "Hangar",
    activity: "Air Freight source mission",
    timerType: "Mission time limit",
    duration: "20 or 30 min",
    minMinutes: 20,
    trigger: "You launch an Air Freight Cargo source mission.",
    scope: "activity",
    scopeLabel: "Current source mission",
    parallel: "no",
    parallelLabel: "No — finish or fail the active source mission.",
    conditions: "Most missions allow 30 minutes; Cargo Planes variants use 20 minutes.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Air Freight Cargo", url: "https://gta.fandom.com/wiki/Air_Freight_Cargo" }],
    verified: "2026-08-30"
  },
  {
    id: "hangar-staff-source",
    category: "Hangar",
    activity: "Rooster cargo sourcing",
    timerType: "Passive production",
    duration: "48 min",
    minMinutes: 48,
    trigger: "You pay Rooster McCraw to source Hangar cargo.",
    scope: "property",
    scopeLabel: "Your Hangar",
    parallel: "yes",
    parallelLabel: "Yes — Rooster works while you do other activities.",
    conditions: "Normal sourcing returns after one in-game day. Event weeks may halve the timer or change the number of crates.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Air Freight Cargo event data", url: "https://gta.fandom.com/wiki/Air_Freight_Cargo_Week_(March_2025)" }],
    verified: "2026-08-30"
  },
  {
    id: "agency-security-cooldown",
    category: "Agency",
    activity: "Security Contracts",
    timerType: "Activity cooldown",
    duration: "5 min",
    minMinutes: 5,
    trigger: "A Security Contract is completed successfully.",
    scope: "activity",
    scopeLabel: "Agency Security Contracts",
    parallel: "yes",
    parallelLabel: "Yes — Payphone Hits and unrelated businesses remain available.",
    conditions: "The cooldown follows successful completion before Franklin can provide another contract.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Security Contracts", url: "https://gta.fandom.com/wiki/Security_Contracts" }],
    verified: "2026-08-30"
  },
  {
    id: "agency-security-limit",
    category: "Agency",
    activity: "Security Contract mission",
    timerType: "Mission time limit",
    duration: "30 min",
    minMinutes: 30,
    trigger: "A Security Contract begins.",
    scope: "activity",
    scopeLabel: "Current Security Contract",
    parallel: "no",
    parallelLabel: "No — the active contract must finish first.",
    conditions: "The game presents a five-minute warning near the end. Some variants contain shorter objective phases within the overall limit.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Security Contracts", url: "https://gta.fandom.com/wiki/Security_Contracts" }],
    verified: "2026-08-30"
  },
  {
    id: "payphone-hit-cooldown",
    category: "Agency",
    activity: "Payphone Hits",
    timerType: "Activity cooldown",
    duration: "10 min",
    minMinutes: 10,
    trigger: "A Payphone Hit is completed.",
    scope: "activity",
    scopeLabel: "Payphone Hits",
    parallel: "yes",
    parallelLabel: "Yes — use the wait for Security Contracts or business work.",
    conditions: "The current 10-minute value replaced older longer cooldowns; old guides commonly show 48 minutes.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Payphone Hits", url: "https://gta.fandom.com/wiki/Payphone_Hits" }],
    verified: "2026-08-30"
  },
  {
    id: "payphone-hit-limit",
    category: "Agency",
    activity: "Payphone Hit mission",
    timerType: "Mission time limit",
    duration: "15 min",
    minMinutes: 15,
    trigger: "You answer or request a Payphone Hit.",
    scope: "activity",
    scopeLabel: "Current Payphone Hit",
    parallel: "no",
    parallelLabel: "No — complete or fail the hit first.",
    conditions: "The assassination bonus method must be completed inside the same job window.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Payphone Hits", url: "https://gta.fandom.com/wiki/Payphone_Hits" }],
    verified: "2026-08-30"
  },
  {
    id: "agency-safe",
    category: "Agency",
    activity: "Agency safe income",
    timerType: "Passive income",
    duration: "48 min",
    minMinutes: 48,
    trigger: "An in-game day passes while the Agency can generate income.",
    scope: "property",
    scopeLabel: "Your Agency safe",
    parallel: "yes",
    parallelLabel: "Yes — income accrues during normal online play.",
    conditions: "The daily amount rises with completed Security Contracts and stops when the safe reaches its cap.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Security Contracts", url: "https://gta.fandom.com/wiki/Security_Contracts" }, { label: "PC Gamer — GTA Online money guide", url: "https://www.pcgamer.com/how-to-make-money-in-gta-online/" }],
    verified: "2026-08-30"
  },
  {
    id: "dre-contract-cooldown",
    category: "Agency",
    activity: "The Data Leaks / Dr. Dre VIP Contract",
    timerType: "Activity cooldown",
    duration: "About 48 min",
    minMinutes: 48,
    trigger: "Don't F*ck With Dre is completed as host.",
    scope: "activity",
    scopeLabel: "Host replay of the VIP Contract",
    parallel: "yes",
    parallelLabel: "Yes — Agency side work and other businesses remain available.",
    conditions: "Franklin contacts the host after roughly one in-game day. Title Update 1.73 also applies a weekly first-completion reward cadence to this finale.",
    evidence: "crosschecked",
    sources: [{ label: "Current Agency guide", url: "https://racoon.gg/gta-v/blog/gta-online-agency-vip-contract-guide" }, { label: "Rockstar Title Update 1.73", url: "https://support.rockstargames.com/articles/4vRqEDvjUs9h7nqRUgc8YO/gtav-title-update-1-73-notes-ps5-ps4-xbox-series-x-or-s-xbox-one-pc-enhanced-legacy" }],
    verified: "2026-08-30"
  },
  {
    id: "nightclub-safe",
    category: "Nightclub",
    activity: "Nightclub popularity income",
    timerType: "Passive income",
    duration: "48 min",
    minMinutes: 48,
    trigger: "An in-game day passes while the Nightclub is operating.",
    scope: "property",
    scopeLabel: "Your Nightclub safe",
    parallel: "yes",
    parallelLabel: "Yes — income accrues while you play other content.",
    conditions: "The amount depends on popularity and stops at the safe cap. Popularity decays each in-game day.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Nightclubs", url: "https://gta.fandom.com/wiki/Nightclubs" }],
    verified: "2026-08-30"
  },
  {
    id: "nightclub-security-job",
    category: "Nightclub",
    activity: "Nightclub Security Job arrival",
    timerType: "Availability check",
    duration: "48 min",
    minMinutes: 48,
    trigger: "Marcel offers an eject-troublemaker or deliver-VIP job in the club.",
    scope: "property",
    scopeLabel: "Your Nightclub",
    parallel: "yes",
    parallelLabel: "Yes — ignoring or failing the job does not lock other work.",
    conditions: "The timer starts when Marcel's text arrives, independent of completing, failing, or ignoring the job. Popularity must be above zero.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Nightclub Management", url: "https://gta.fandom.com/wiki/Nightclubs/Nightclub_Management" }],
    verified: "2026-08-30"
  },
  {
    id: "nightclub-goods",
    category: "Nightclub",
    activity: "Nightclub warehouse goods — per crate",
    timerType: "Passive production",
    duration: "15 min–2 hr 20 min",
    minMinutes: 15,
    trigger: "A technician is assigned to an eligible active feeder business.",
    scope: "property",
    scopeLabel: "Per technician and goods type",
    parallel: "yes",
    parallelLabel: "Yes — goods accrue during other online activities.",
    conditions: "Without / with the Nightclub equipment upgrade: Cargo 140/70 min; Sporting Goods 80/40; South American Imports 240/120; Pharmaceutical 120/60; Organic 40/20; Printing 30/15; Cash 60/30. Feeder stock is not consumed.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Nightclubs", url: "https://gta.fandom.com/wiki/Nightclubs" }, { label: "GTA BOOM — Nightclub warehouse guide", url: "https://www.gtaboom.com/gta-online-nightclub-warehouse-management-and-profit-guide-b639" }],
    verified: "2026-08-30"
  },
  {
    id: "acid-production",
    category: "Acid Lab",
    activity: "Acid Lab — full stock production",
    timerType: "Passive production",
    duration: "6 hr / 4 hr upgraded",
    minMinutes: 240,
    trigger: "The Acid Lab has supplies and production starts.",
    scope: "property",
    scopeLabel: "Your Acid Lab",
    parallel: "yes",
    parallelLabel: "Yes — production runs during other online activities.",
    conditions: "Standard equipment fills 160 units in 6 hours; the equipment upgrade takes 4 hours. A production boost reduces a full cycle to about 4.5 or 3 hours respectively.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Acid Product", url: "https://gta.fandom.com/wiki/Acid_Product" }],
    verified: "2026-08-30"
  },
  {
    id: "acid-boost-reset",
    category: "Acid Lab",
    activity: "Acid production boost",
    timerType: "Daily reset",
    duration: "Once daily — 06:00 UTC reset",
    minMinutes: 1440,
    trigger: "You activate the chemical-table production boost.",
    scope: "account",
    scopeLabel: "Your Acid Lab boost",
    parallel: "yes",
    parallelLabel: "Yes — boosted production continues in the background.",
    conditions: "The boost lasts until 80 stock units are produced or 24 real hours pass, whichever happens first. Clock shown as UTC; older sources may say GMT.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Acid Product", url: "https://gta.fandom.com/wiki/Acid_Product" }],
    verified: "2026-08-30"
  },
  {
    id: "fooligan-job",
    category: "Acid Lab",
    activity: "Fooligan Jobs",
    timerType: "Activity cooldown",
    duration: "48 min",
    minMinutes: 48,
    trigger: "A Fooligan Job from Dax is completed successfully.",
    scope: "activity",
    scopeLabel: "Dax's Request Work",
    parallel: "yes",
    parallelLabel: "Yes — Acid production and other work continue.",
    conditions: "Ten completed Fooligan Jobs unlock the Acid Lab equipment upgrade; the cooldown applies after each successful job.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Fooligan Jobs", url: "https://gta.fandom.com/wiki/Fooligan_Jobs" }],
    verified: "2026-08-30"
  },
  {
    id: "auto-shop-arrival",
    category: "Auto Shop",
    activity: "Customer car arrival",
    timerType: "Availability check",
    duration: "48 min / 24 min with 2 lifts",
    minMinutes: 24,
    trigger: "A customer vehicle arrives at the Auto Shop.",
    scope: "property",
    scopeLabel: "Your Auto Shop",
    parallel: "yes",
    parallelLabel: "Yes — the next eligibility check runs during normal play.",
    conditions: "After the minimum wait, arrival is a 50% check, followed by a possible 0–10 minute delay when you are not in a mission or inside the shop. A failed check repeats the timer.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Auto Shop Service", url: "https://gta.fandom.com/wiki/Auto_Shop_Service" }],
    verified: "2026-08-30"
  },
  {
    id: "auto-shop-delivery",
    category: "Auto Shop",
    activity: "Customer car delivery",
    timerType: "Mission time limit",
    duration: "30 min",
    minMinutes: 30,
    trigger: "You choose to deliver a serviced customer car personally.",
    scope: "activity",
    scopeLabel: "Current customer delivery",
    parallel: "no",
    parallelLabel: "No — finish or abandon the vehicle delivery.",
    conditions: "The timer is initially hidden and appears with five minutes remaining. Destroying the car returns it to the Auto Shop rather than permanently losing it.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Auto Shop Service", url: "https://gta.fandom.com/wiki/Auto_Shop_Service" }],
    verified: "2026-08-30"
  },
  {
    id: "exotic-exports-reset",
    category: "Auto Shop",
    activity: "Exotic Exports list",
    timerType: "Daily reset",
    duration: "Daily at 06:00 UTC",
    minMinutes: 1440,
    trigger: "The global daily reset occurs.",
    scope: "global",
    scopeLabel: "Daily vehicle list",
    parallel: "yes",
    parallelLabel: "Yes — the list stays active while you do other work.",
    conditions: "The list contains 10 vehicles. Session and spawn bugs can delay a visible refresh or leave an older list active.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Exotic Exports", url: "https://gta.fandom.com/wiki/Exotic_Exports_(GTA_Online)" }],
    verified: "2026-08-30"
  },
  {
    id: "auto-shop-contract-repeat",
    category: "Auto Shop",
    activity: "Auto Shop Robbery Contract repeat",
    timerType: "Activity cooldown",
    duration: "About 48 min for the same contract",
    minMinutes: 48,
    trigger: "An Auto Shop Robbery Contract finale is completed.",
    scope: "activity",
    scopeLabel: "Per Contract job",
    parallel: "yes",
    parallelLabel: "Yes — choose another board contract or other business work.",
    conditions: "The board offers up to three contracts. Current community checks consistently report one in-game day before repeating the same Contract; board composition can change by session.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Contracts", url: "https://gta.fandom.com/wiki/Contracts_(mission_series)" }, { label: "Current community discussion", url: "https://www.reddit.com/r/gtaonline/comments/1tjvdd7/the_auto_shop_contracts_are_paying_double_this/" }],
    verified: "2026-08-30"
  },
  {
    id: "salvage-robbery-reset",
    category: "Salvage Yard",
    activity: "Salvage Yard Robbery targets",
    timerType: "Weekly reset",
    duration: "Weekly event reset",
    minMinutes: 10080,
    trigger: "GTA Online's weekly event changes.",
    scope: "global",
    scopeLabel: "Weekly set of three vehicles",
    parallel: "yes",
    parallelLabel: "Yes — complete the available robberies in any order during the week.",
    conditions: "Each target vehicle can be robbed once in that rotation. The set normally changes with the Thursday event update; Rockstar can shift an event window.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Salvage Yard Robberies", url: "https://gta.fandom.com/wiki/Salvage_Yard_Robberies" }],
    verified: "2026-08-30"
  },
  {
    id: "tow-truck-cooldown",
    category: "Salvage Yard",
    activity: "Tow Truck Service",
    timerType: "Activity cooldown",
    duration: "2 min",
    minMinutes: 2,
    trigger: "A Tow Truck Service mission ends.",
    scope: "activity",
    scopeLabel: "Tow Truck Service",
    parallel: "yes",
    parallelLabel: "Yes — the Salvage Yard and other businesses remain usable.",
    conditions: "The two-minute cooldown was added after the original release. Two cars can be in the salvage process at once.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Tow Truck Service", url: "https://gta.fandom.com/wiki/Tow_Truck_Service" }],
    verified: "2026-08-30"
  },
  {
    id: "tow-truck-salvage",
    category: "Salvage Yard",
    activity: "Tow Truck vehicle salvage",
    timerType: "Passive production",
    duration: "96 min / 48 min with staff",
    minMinutes: 48,
    trigger: "A towed vehicle is delivered to the Salvage Yard.",
    scope: "property",
    scopeLabel: "Per salvage bay vehicle",
    parallel: "yes",
    parallelLabel: "Yes — salvage progresses during other work and while offline.",
    conditions: "The Staff upgrade halves the two-in-game-day process. Up to two vehicles can be processed concurrently.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Tow Truck Service", url: "https://gta.fandom.com/wiki/Tow_Truck_Service" }, { label: "GTA BOOM — Salvage Yard guide", url: "https://www.gtaboom.com/gta-online-salvage-yard-business-guide-passive-income-563a/" }],
    verified: "2026-08-30"
  },
  {
    id: "bail-standard-refresh",
    category: "Bail Office",
    activity: "Standard bounty targets",
    timerType: "Availability check",
    duration: "Every 1 hr",
    minMinutes: 60,
    trigger: "The Bail Office's hourly target rotation refreshes.",
    scope: "global",
    scopeLabel: "Set of three Standard Targets",
    parallel: "yes",
    parallelLabel: "Yes — pursue other work while the next board rotates.",
    conditions: "The three blue Standard Targets refresh together. A visible refresh can require leaving/re-entering the computer or changing session.",
    evidence: "official",
    sources: [{ label: "Rockstar Title Update 1.69", url: "https://support.rockstargames.com/articles/eUgRHVRSN2V9gimBT32YX/gtav-title-update-1-69-notes-ps5-ps4-xbox-series-x-s-xbox-one-pc" }, { label: "GamesRadar — bounty guide", url: "https://www.gamesradar.com/games/grand-theft-auto/gta-online-bounty-hunting/" }],
    verified: "2026-08-30"
  },
  {
    id: "bail-most-wanted",
    category: "Bail Office",
    activity: "Most Wanted bounty",
    timerType: "Daily reset",
    duration: "Once per daily reset",
    minMinutes: 1440,
    trigger: "The daily Most Wanted target rotation changes.",
    scope: "account",
    scopeLabel: "One Most Wanted target per day",
    parallel: "yes",
    parallelLabel: "Yes — Standard Targets and other businesses remain available.",
    conditions: "The red target can be completed once in the current daily rotation. Server refresh can occasionally appear delayed.",
    evidence: "official",
    sources: [{ label: "Rockstar Title Update 1.69", url: "https://support.rockstargames.com/articles/eUgRHVRSN2V9gimBT32YX/gtav-title-update-1-69-notes-ps5-ps4-xbox-series-x-s-xbox-one-pc" }, { label: "GTA BOOM — Bail Office guide", url: "https://www.gtaboom.com/bottom-dollar-bounties-business-guide-137f" }],
    verified: "2026-08-30"
  },
  {
    id: "bail-agents",
    category: "Bail Office",
    activity: "Bail Enforcement Agents",
    timerType: "Passive production",
    duration: "About 48 min",
    minMinutes: 48,
    trigger: "You send a hired agent out from the Bail Office.",
    scope: "property",
    scopeLabel: "Per hired agent",
    parallel: "yes",
    parallelLabel: "Yes — agents work while you pursue other activities.",
    conditions: "Each agent operates independently and returns money to the safe. Rockstar does not publish an exact visible countdown; one in-game day is the current community-tested interval.",
    evidence: "crosschecked",
    sources: [{ label: "GTA BOOM — Bail Office guide", url: "https://www.gtaboom.com/bottom-dollar-bounties-business-guide-137f" }, { label: "Current community timing", url: "https://steamcommunity.com/app/271590/discussions/0/4756452114758296406/" }],
    verified: "2026-08-30"
  },
  {
    id: "fib-files-cooldown",
    category: "Garment Factory",
    activity: "FIB Files",
    timerType: "Activity cooldown",
    duration: "5 min",
    minMinutes: 5,
    trigger: "An FIB File finale is completed.",
    scope: "global",
    scopeLabel: "Across FIB Files",
    parallel: "yes",
    parallelLabel: "Yes — all unrelated businesses remain available.",
    conditions: "The same File cannot be selected back-to-back; rotate to another regular File after the five-minute wait.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — The FIB Files", url: "https://gta.fandom.com/wiki/The_FIB_Files" }],
    verified: "2026-08-30"
  },
  {
    id: "fib-priority-weekly",
    category: "Garment Factory",
    activity: "Priority FIB File",
    timerType: "Weekly reset",
    duration: "Once per weekly event",
    minMinutes: 10080,
    trigger: "You complete the File currently marked as Priority.",
    scope: "account",
    scopeLabel: "Weekly Priority File completion",
    parallel: "yes",
    parallelLabel: "Yes — regular Files remain repeatable after their cooldowns.",
    conditions: "The Priority File changes with the event week and can be completed once for its increased reward before the next refresh.",
    evidence: "official",
    sources: [{ label: "Rockstar Title Update 1.70", url: "https://support.rockstargames.com/articles/2Bg4OssFDYK9cgg0CBChnU/gtav-title-update-1-70-notes-ps5-ps4-xbox-series-x-s-xbox-one-pc" }, { label: "GTA Wiki — The FIB Files", url: "https://gta.fandom.com/wiki/The_FIB_Files" }],
    verified: "2026-08-30"
  },
  {
    id: "garment-safe",
    category: "Garment Factory",
    activity: "Garment Factory safe income",
    timerType: "Passive income",
    duration: "48 min",
    minMinutes: 48,
    trigger: "An in-game day passes while the property can generate income.",
    scope: "property",
    scopeLabel: "Garment Factory safe",
    parallel: "yes",
    parallelLabel: "Yes — income accrues during other online play.",
    conditions: "The safe adds a small randomized amount and stops at capacity. Event weeks may temporarily multiply passive income.",
    evidence: "crosschecked",
    sources: [{ label: "GTA BOOM — Agents of Sabotage guide", url: "https://www.gtaboom.com/agents-of-sabotage-complete-guide-e147" }],
    verified: "2026-08-30"
  },
  {
    id: "cayo-replay",
    category: "Heists",
    activity: "Cayo Perico Heist replay",
    timerType: "Activity cooldown",
    duration: "144 min solo / 48 min with crew",
    minMinutes: 48,
    trigger: "The host completes the Cayo Perico finale.",
    scope: "account",
    scopeLabel: "Host's next Cayo setup",
    parallel: "yes",
    parallelLabel: "Yes — the timer continues during other work and while offline.",
    conditions: "Solo completion uses three in-game days. A finale completed with 2–4 players uses one in-game day.",
    evidence: "official",
    sources: [{ label: "Rockstar Support — replaying solo Cayo", url: "https://support.rockstargames.com/articles/1USXP7YjmcXFt6bz2qjTmZ/replaying-the-solo-cayo-perico-heist-finale-in-grand-theft-auto-online" }, { label: "GTA Wiki — Cayo finale", url: "https://gta.fandom.com/wiki/The_Cayo_Perico_Heist/Finale" }],
    verified: "2026-08-30"
  },
  {
    id: "cayo-hard-mode",
    category: "Heists",
    activity: "Cayo Perico Hard Mode activation",
    timerType: "Availability window",
    duration: "48 min window",
    minMinutes: 48,
    trigger: "Pavel messages that the next Cayo Perico Heist is available after the replay cooldown.",
    scope: "account",
    scopeLabel: "Host's next Cayo setup fee",
    parallel: "limited",
    parallelLabel: "Limited — other work is possible, but pay the setup fee before the window closes.",
    conditions: "Paying the setup fee at the Kosatka inside this window enables Hard Mode for the next run.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Cayo finale", url: "https://gta.fandom.com/wiki/The_Cayo_Perico_Heist/Finale" }, { label: "Current Cayo walkthrough", url: "https://www.six-central.com/guides/cayo-perico-heist" }],
    verified: "2026-08-30"
  },
  {
    id: "cluckin-bell-replay",
    category: "Heists",
    activity: "Cluckin' Bell Farm Raid replay",
    timerType: "Activity cooldown",
    duration: "About 60 min",
    minMinutes: 60,
    trigger: "The host completes Scene of the Crime.",
    scope: "account",
    scopeLabel: "Host's raid strand",
    parallel: "yes",
    parallelLabel: "Yes — the host can run unrelated missions and businesses.",
    conditions: "The cooldown gates restarting the full raid strand, not only the finale. Title Update 1.73 also adds a weekly first-completion reward cadence.",
    evidence: "crosschecked",
    sources: [{ label: "GTA BOOM — Cluckin' Bell FAQ", url: "https://www.gtaboom.com/cluckin-bell-farm-raid-payout-cooldown-time-rewards-and-other-faqs-e657/" }, { label: "Rockstar — raid announcement", url: "https://www.rockstargames.com/newswire/article/39ok12a82k4537/gta-online-the-cluckin-bell-farm-raid-now-available" }],
    verified: "2026-08-30"
  },
  {
    id: "heist-weekly-reward",
    category: "Heists",
    activity: "Heist and raid weekly first-completion bonus",
    timerType: "Weekly reset",
    duration: "Weekly event reset",
    minMinutes: 10080,
    trigger: "The host completes an eligible finale in the current event week.",
    scope: "account",
    scopeLabel: "Per eligible finale, per host",
    parallel: "yes",
    parallelLabel: "Yes — each listed activity has its own weekly completion state.",
    conditions: "Title Update 1.73 applies the cadence to Original Heists, Doomsday Acts, Casino, Cluckin' Bell, Data Leaks, Oscar Guzman Flies Again, and KnoWay Out. Repeat payouts in the same week are reduced.",
    evidence: "official",
    sources: [{ label: "Rockstar Title Update 1.73", url: "https://support.rockstargames.com/articles/4vRqEDvjUs9h7nqRUgc8YO/gtav-title-update-1-73-notes-ps5-ps4-xbox-series-x-or-s-xbox-one-pc-enhanced-legacy" }],
    verified: "2026-08-30"
  },
  {
    id: "cayo-target-cadence",
    category: "Heists",
    activity: "Cayo Perico target appearance cadence",
    timerType: "Weekly reset",
    duration: "Weekly event reset",
    minMinutes: 10080,
    trigger: "The weekly GTA Online event period refreshes.",
    scope: "account",
    scopeLabel: "Host's repeated Cayo target odds",
    parallel: "yes",
    parallelLabel: "Yes — this affects target appearance odds, not the shorter replay cooldown.",
    conditions: "Title Update 1.73 moved repeated-completion Primary and Secondary Target appearance rates to the same weekly cadence as the other listed finales.",
    evidence: "official",
    sources: [{ label: "Rockstar Title Update 1.73", url: "https://support.rockstargames.com/articles/4vRqEDvjUs9h7nqRUgc8YO/gtav-title-update-1-73-notes-ps5-ps4-xbox-series-x-or-s-xbox-one-pc-enhanced-legacy" }],
    verified: "2026-08-30"
  },
  {
    id: "kortz-replay",
    category: "Heists",
    activity: "Kortz Center Heist replay",
    timerType: "Variable gate",
    duration: "Raf call — no dependable fixed clock",
    minMinutes: 10,
    trigger: "The host completes the Kortz Center finale and waits for Raf's replay call.",
    scope: "account",
    scopeLabel: "Host's next Kortz setup",
    parallel: "yes",
    parallelLabel: "Yes — run other content until Raf contacts you.",
    conditions: "Rockstar documents the heist but not a fixed replay duration. Current specialist testing conflicts, so this database intentionally does not claim an exact number. Starting within about 15 minutes of Raf's call enables Hard Mode.",
    evidence: "variable",
    sources: [{ label: "Rockstar Title Update 1.73", url: "https://support.rockstargames.com/articles/4vRqEDvjUs9h7nqRUgc8YO/gtav-title-update-1-73-notes-ps5-ps4-xbox-series-x-or-s-xbox-one-pc-enhanced-legacy" }, { label: "Current hands-on Kortz guide", url: "https://www.gtaboss.gg/gta-5-online/guides/everything-you-need-to-know-about-the-kortz-center-heist" }],
    verified: "2026-08-30"
  },
  {
    id: "money-fronts-laundering",
    category: "Money Fronts",
    activity: "Money Laundering Missions",
    timerType: "Activity cooldown",
    duration: "No normal fixed cooldown",
    minMinutes: 0,
    trigger: "A laundering mission ends and Heat is added to the relevant front.",
    scope: "property",
    scopeLabel: "Heat is tracked per front",
    parallel: "limited",
    parallelLabel: "Limited — missions can repeat until Heat blocks or slows the front.",
    conditions: "Legal front work reduces Heat. The Car Wash, Smoke on the Water, and Higgins Helitours track Heat separately; a maxed front must cool before it produces normally.",
    evidence: "crosschecked",
    sources: [{ label: "Rockstar — Money Fronts", url: "https://www.rockstargames.com/newswire/article/51322o2k393kka/gta-online-money-fronts-now-available" }, { label: "PC Gamer — Money Fronts guide", url: "https://www.pcgamer.com/games/grand-theft-auto/gta-online-money-fronts-guide-maximize-profits/" }],
    verified: "2026-08-30"
  },
  {
    id: "money-fronts-safe",
    category: "Money Fronts",
    activity: "Car Wash safe income tick",
    timerType: "Passive income",
    duration: "48 min",
    minMinutes: 48,
    trigger: "An in-game day passes while front income is active.",
    scope: "property",
    scopeLabel: "Shared Car Wash safe",
    parallel: "yes",
    parallelLabel: "Yes — legal and illegal front activity can be mixed with other businesses.",
    conditions: "Income depends on owned linked operations and Heat. Excess Heat can suppress passive income until reduced through legal work.",
    evidence: "crosschecked",
    sources: [{ label: "Rockstar — Money Fronts", url: "https://www.rockstargames.com/newswire/article/51322o2k393kka/gta-online-money-fronts-now-available" }, { label: "PC Gamer — Money Fronts guide", url: "https://www.pcgamer.com/games/grand-theft-auto/gta-online-money-fronts-guide-maximize-profits/" }],
    verified: "2026-08-30"
  },
  {
    id: "street-car-sale",
    category: "Daily Activities",
    activity: "Street vehicle sale at Los Santos Customs",
    timerType: "Activity cooldown",
    duration: "48 min",
    minMinutes: 48,
    trigger: "You sell an eligible stolen street vehicle.",
    scope: "account",
    scopeLabel: "Character vehicle-sale eligibility",
    parallel: "yes",
    parallelLabel: "Yes — only another eligible street-car sale is blocked.",
    conditions: "This repeat timer is separate from Rockstar's anti-exploit daily sale limit for owned vehicles.",
    evidence: "crosschecked",
    sources: [{ label: "GTA Wiki — Los Santos Customs", url: "https://gta.fandom.com/wiki/Los_Santos_Customs" }, { label: "Rockstar — daily vehicle sale limit", url: "https://support.rockstargames.com/articles/5vCxkoPcwklTXHE5k2Qwcd/daily-limit-reached-when-selling-vehicles-in-grand-theft-auto-online" }],
    verified: "2026-08-30"
  },
  {
    id: "mechanic-call",
    category: "Daily Activities",
    activity: "Mechanic vehicle request",
    timerType: "Activity cooldown",
    duration: "2 min",
    minMinutes: 2,
    trigger: "The Mechanic delivers a requested personal vehicle.",
    scope: "account",
    scopeLabel: "Mechanic phone service",
    parallel: "yes",
    parallelLabel: "Yes — gameplay continues normally between vehicle requests.",
    conditions: "This is the service cooldown between Mechanic calls, not the shorter personal-vehicle Interaction Menu behavior.",
    evidence: "official",
    sources: [{ label: "Rockstar Support — finding vehicles", url: "https://support.rockstargames.com/articles/375Mcz7Cc3wFa6YIG9gES0/finding-your-lost-or-misplaced-vehicles-in-grand-theft-auto-online" }],
    verified: "2026-08-30"
  }
];
