import { bearingDegrees, compassDirection, destinations, displayEmoji, districts, estimateTrip, findCandidates, findStartMatches, formatDuration, googleDirectionsUrl, googlePlaceUrl, haversineKm, localizeSourceMeta, localizeSourceUrl, normalizePlaceName, pickDestination, starts, stopMapPoints, stopMapQueries } from "./engine.js?v=15";

const results = [];
const assert = (condition, message = "Assertion failed") => { if (!condition) throw new Error(message); };
const test = (name, run) => { try { run(); results.push({ name, passed: true }); } catch (error) { results.push({ name, passed: false, error: error.message }); } };
const lisbon = starts.find((start) => start.id === "lisbon");
const porto = starts.find((start) => start.id === "porto");

test("All 18 mainland districts are available", () => assert(districts.length === 18, districts.length));
test("Every starting locality belongs to a known district", () => assert(starts.every((start) => districts.some((district) => district.id === start.districtId))));
test("Starting catalogue has broad mainland coverage", () => assert(starts.length >= 280, starts.length));
test("Every district has at least ten starting places", () => assert(districts.every((district) => starts.filter((start) => start.districtId === district.id).length >= 10)));
test("Starting place IDs are unique", () => assert(new Set(starts.map((start) => start.id)).size === starts.length));
test("Starting coordinates stay within mainland Portugal", () => assert(starts.every((start) => start.lat >= 36.9 && start.lat <= 42.2 && start.lon >= -9.6 && start.lon <= -6.1)));
test("Faro includes Sagres and Vila Real de Santo António", () => { const faro = starts.filter((start) => start.districtId === "faro"); assert(faro.some((start) => start.id === "sagres")); assert(faro.some((start) => start.id === "vila-real-de-santo-antonio")); });
test("Locality search ignores accents and letter case", () => assert(normalizePlaceName("SÃO BRÁS") === "sao bras"));
test("Locality search finds close spellings", () => assert(findStartMatches("faro", "vil real santo antonio", 3).some((start) => start.id === "vila-real-de-santo-antonio")));
test("Santarém includes Torres Novas and detailed locality choices", () => { const localities = starts.filter((start) => start.districtId === "santarem"); assert(localities.length >= 10); assert(localities.some((start) => start.id === "torres-novas")); });
test("Expanded destination collection has at least 99 options", () => assert(destinations.length >= 99, destinations.length));
test("Destination IDs are unique", () => assert(new Set(destinations.map((item) => item.id)).size === destinations.length));
test("Every destination has bilingual content and a source", () => assert(destinations.every((item) => item.source && item.copy?.en && item.copy?.pt && item.stops?.en?.length === 3 && item.stops?.pt?.length === 3)));
test("Every destination resolves an HTTPS source in both languages", () => assert(destinations.every((item) => ["en", "pt"].every((language) => localizeSourceUrl(item.source, language, item.id).startsWith("https://")))));
test("Every mini-plan stop has a curated map target", () => assert(destinations.every((item) => stopMapQueries[item.id]?.length === 3 && stopMapQueries[item.id].every(Boolean))));
test("Every mini-plan stop has a valid coordinate anchor", () => assert(destinations.every((item) => stopMapPoints[item.id]?.length === 3 && stopMapPoints[item.id].every((point) => Number.isFinite(point.lat) && Number.isFinite(point.lon) && point.lat >= 36.9 && point.lat <= 42.2 && point.lon >= -9.6 && point.lon <= -6.1))));
test("Portinho da Arrábida uses its exact place target", () => assert(stopMapQueries.arrabida[2] === "Portinho da Arrábida"));
test("Portinho da Arrábida map anchor is on the cove", () => assert(haversineKm(stopMapPoints.arrabida[2], { lat: 38.4754, lon: -8.9844 }) < 0.2));
test("Destination sources include official, independent, and community ideas", () => { const types = new Set(destinations.flatMap((item) => typeof item.sourceType === "object" ? Object.values(item.sourceType) : [item.sourceType ?? "official"])); assert(["official", "independent", "community"].every((type) => types.has(type))); });
test("Legacy Visit Portugal links were removed", () => assert(destinations.every((item) => Object.values(typeof item.source === "object" ? item.source : { default: item.source }).every((url) => !url.includes("/NR/exeres/")))));
test("Visit Portugal source links use the correct Portuguese locale", () => { const source = "https://www.visitportugal.com/en/node/135553"; assert(localizeSourceUrl(source, "pt") === "https://www.visitportugal.com/pt-pt/node/135553"); assert(localizeSourceUrl(source, "en") === source); });
test("Arrábida has a stable Portuguese source page", () => { const source = destinations.find((item) => item.id === "arrabida").source; assert(localizeSourceUrl(source, "pt", "arrabida") === "https://pt.wikipedia.org/wiki/Parque_Natural_da_Arr%C3%A1bida"); });
test("Bilingual source objects select an exact language page", () => { const source = destinations.find((item) => item.id === "monsanto").source; assert(localizeSourceUrl(source, "pt") === "https://aldeiashistoricasdeportugal.com/pt/aldeia/monsanto/"); });
test("Bilingual source labels follow the selected language", () => { const destination = destinations.find((item) => item.id === "monsanto"); assert(localizeSourceMeta(destination.sourceLabel, "en") === "Historical Villages of Portugal"); assert(localizeSourceMeta(destination.sourceLabel, "pt") === "Aldeias Históricas de Portugal"); });
test("Main Google route uses exact coordinates", () => { const destination = destinations.find((item) => item.id === "arrabida"); const url = new URL(googleDirectionsUrl(lisbon, destination, "pt")); assert(url.searchParams.get("origin") === `${lisbon.lat},${lisbon.lon}`); assert(url.searchParams.get("destination") === `${destination.lat},${destination.lon}`); assert(url.searchParams.get("hl") === "pt-PT"); });
test("Mini-plan Google link uses the documented API and exact anchor", () => { const url = new URL(googlePlaceUrl(stopMapQueries.arrabida[2], stopMapPoints.arrabida[2], "en")); assert(url.searchParams.get("api") === "1"); assert(url.searchParams.get("query") === "38.475355,-8.98436"); assert(url.searchParams.get("hl") === "en"); });
test("Every mini-plan link uses its exact coordinate anchor", () => assert(destinations.every((item) => stopMapPoints[item.id].every((point, index) => { const url = new URL(googlePlaceUrl(stopMapQueries[item.id][index], point, "pt")); return url.searchParams.get("api") === "1" && url.searchParams.get("query") === `${point.lat},${point.lon}` && url.searchParams.get("hl") === "pt-PT"; }))));
test("Newer unsupported emoji have compatible display fallbacks", () => { const unsupported = new Set(["🧱", "🧭", "🥾", "🪨", "🪁", "🪵", "🦩"]); const casal = destinations.find((item) => item.id === "casal-sao-simao"); assert(displayEmoji(casal) === "⛰️"); assert(destinations.every((item) => !unsupported.has(displayEmoji(item)))); });
test("Lisbon to Porto straight-line distance is plausible", () => { const distance = haversineKm(lisbon, porto); assert(distance > 260 && distance < 290, distance); });
test("Porto is north of Lisbon", () => assert(compassDirection(bearingDegrees(lisbon, porto)) === "N"));
test("Trip estimates exceed straight-line distance", () => assert(estimateTrip(lisbon, porto).distanceKm > haversineKm(lisbon, porto)));
test("Trip duration is positive", () => assert(estimateTrip(lisbon, porto).durationMinutes > 0));
test("English duration is formatted", () => assert(formatDuration(135, "en") === "2h 15"));
test("Portuguese duration is formatted", () => assert(formatDuration(60, "pt") === "1h"));
test("History filter returns matching destinations", () => assert(findCandidates({ origin: lisbon, maxDistance: 180, vibe: "history" }).every((item) => item.vibes.includes("history"))));
test("Drive-time filter respects the one-way minute limit", () => assert(findCandidates({ origin: lisbon, maxDuration: 90 }).every((item) => item.trip.durationMinutes <= 90)));
test("Random picker honours deterministic random", () => { const result = pickDestination({ origin: lisbon, maxDistance: 180, random: () => 0 }); assert(Boolean(result?.id)); });
test("Excluded destination is avoided when alternatives exist", () => { const first = pickDestination({ origin: lisbon, maxDistance: 180, random: () => 0 }); const second = pickDestination({ origin: lisbon, maxDistance: 180, excludeId: first.id, random: () => 0 }); assert(first.id !== second.id); });

const passed = results.filter((result) => result.passed).length;
document.querySelector("#test-count").textContent = `${results.length} tests`;
document.querySelector("#passed-count").textContent = `${passed} passed`;
document.querySelector("#failed-count").textContent = `${results.length - passed} failed`;
document.querySelector("#test-results").innerHTML = results.map((result) => `<li class="${result.passed ? "pass" : "fail"}"><strong>${result.passed ? "PASS" : "FAIL"}</strong> ${result.name}${result.error ? `<small>${result.error}</small>` : ""}</li>`).join("");
